### PR TITLE
[MVN, MVP] Source and destination inverted?!?

### PR DESCRIPTION
**Pull request by Delutto**

### CODE REVIEW

**Comment by Ersanio** [comment]
Thank you for the contribution. I do not know which assembler you have used to verify this. In `getting-started.md`, the tutorial specifically mentions it uses Asar syntax. I tried your changes with [Asar 1.81](https://github.com/RPGHacker/asar/releases/tag/v1.81) and the example code snipped did not copy the bytes from ROM to WRAM. Rather, it went the opposite way (with ultimately no changes taking place, as ROM is read-only).

The syntax for MVN and MVP can be written in two ways: `$xx, $yy`, or `$yyxx`, where `xx` is the destination and `yy` is the source. The `$xx, $yy` syntax is most likely inspired by `MOV dest, src`-styled syntax from other assembly languages.

**Comment by Delutto** [comment]
Strange... MESEN-S trace log shows as MVP src, dest.
xxyy is the byte order on ROM.

**Official documentation from Western Digital:**
image

I think what caused this confusion was this part:
image

**Other documentations**

[Nocash Fullsnes:](https://problemkaputt.de/fullsnes.htm)
Memory Block Transfer Commands
  Opcode   Flags Clks  Native         Nocash                         ;Notes
  44 dd ss  ------  7x  MVP ss,dd   LDDR [dd:Y],[ss:X],A+1  ;DEC X/Y
  54 dd ss  ------  7x  MVN ss,dd   LDIR [dd:Y],[ss:X],A+1   ;INC X/Y


[UnDesbeliever:](https://undisbeliever.net/snesdev/65816-opcodes.html#mvp-block-move-previous)
<html><body>


Syntax | Addressing Mode | Opcode | Bytes | Cycles | Extra
-- | -- | -- | -- | -- | --
MVP srcBank, destBank | Block Move | 44 | 3 |   | 7 per byte moved


</body>
</html>


[FF6Hacking:](https://www.ff6hacking.com/wiki/doku.php?id=ff3:ff3us:doc:snes:opcode#mvp_mvn)
<html><body>
<h2 class="sectionedit64 page-header pb-3 mb-4 mt-5" id="mvp_mvn">MVP, MVN<a class="anchorjs-link " href="https://www.ff6hacking.com/wiki/doku.php?id=ff3:ff3us:doc:snes:opcode#mvp_mvn" aria-label="Anchor link for: mvp_mvn" data-anchorjs-icon="" style="font-family: anchorjs-icons; font-style: normal; font-variant: normal; font-weight: normal; line-height: 1; padding-left: 0.375em;"></a></h2>
<div class="level2">

<p>
Move a block of bytes from a specified address to another address. The X
 register will be the start address to copy from. The Y register will be
 start address to copy to. The C register will be the number of bytes to
 copy minus one.
</p>

<p>
The opcode arguments are the source bank and the destination bank, in this order.
</p>

<p>
MVP must be used if the Y register is greater than the X register. Otherwise, MVN must be used instead.
</p>
<div class="table-responsive">

Opcode | Syntax | Bytes | Notes
-- | -- | -- | --
44 | MVP src,dest | 3 |  
54 | MVN src,dest | 3 |  

</div></div>
</body>
</html>

Maybe a note for non Asar users?
Thanks.

**Comment by Ersanio** [comment]
Looks like the consensus indeed is `src, dest` rather than the other way around, seeing many resources mention it this way. I doubt Asar will ever implement this correct notation, as it would break existing code.

Personally I think the syntax should be kept as-is in the tutorial, but there should indeed be a note for non-Asar users. I'll re-open this PR.

**Comment by Ersanio** [comment]
Closed due to inactivity.

**Pull request closed without merging**
